ahmed_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app1.urls')),
]

app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path("about/", views.about, name='about'),
    path("contact/", views.contact, name='contact'),
    path("dashboard/", views.dashboard, name='dashboard'),
    path("signup/", views.signup, name='signup'),
    path("login/", views.login, name='login'),
    path("logout/", views.logout, name='logout'),
    path("addpost/", views.add_post, name='addpost'),
    path("updatepost/<int:id>/", views.update_post, name='updatepost'),
    path("deletepost/<int:id>/", views.delete_post, name='deletepost'),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class contact(models.Model):
    email = models.EmailField(max_length=254)
    address = models.CharField(max_length=500)
    city = models.CharField(max_length=100) 
    comments = models.CharField(max_length=1000)


class blogs(models.Model):
    usernamee = models.CharField(max_length=250)
    title = models.CharField(max_length=500,)
    description = models.CharField(max_length=1000)
    # ahmed
    

app1/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import contact, blogs
from django.contrib.auth.forms import AuthenticationForm


class contact_form(forms.ModelForm):
    email = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'email'}),label=("Email"),required=True)
    address = forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'address'}),label=("Address"),required=True)
    city = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'city'}),label=("City"),required=True)
    comments = forms.CharField(max_length=1000,widget=forms.Textarea(attrs={'class':'form-control','placeholder':'comments'}),label=("Comments"),required=True)
    
    class Meta: 
        model = contact
        fields = ['email', 'address', 'city', 'comments']

        
class signup_form(UserCreationForm):
    first_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'first name'}),label=("First Name"),required=True)
    last_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'last name'}),label=("Last Name"),required=True)
    username = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'username'}),label=("Username"),required=True)
    email = forms.CharField(max_length=100,widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'email'}),label=("Email"),required=True)
    age = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'age'}),label=('Age'))
    password1 = forms.CharField(max_length=100,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'password'}),label=("Password"))
    password2 = forms.CharField(max_length=100,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'again password'}),label=("Password Confirmation"))
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email', 'age', 'password1','password2')


class login_form(AuthenticationForm):
    username = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'username'}),label=("Username"),required=True)
    password = forms.CharField(max_length=100,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'password'}),label=("Password"),required=True)


class blogs_form(forms.ModelForm):
    title = forms.CharField(max_length=500,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'title'}),label=("Title"),required=True)
    description = forms.CharField(max_length=1000,widget=forms.Textarea(attrs={'class':'form-control','placeholder':'description'}),label=("Description"),required=True)
    class Meta:
        model = blogs
        fields = ('title', 'description')
    

app1/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from .forms import contact_form, signup_form, login_form, blogs_form
from .models import contact, blogs
from django.contrib.auth import authenticate, login as do_login, logout as do_logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import Group
from django.contrib import messages
from django.core.cache import cache
from django.core.paginator import Paginator

# Create your views here.

def home(request):
    data = blogs.objects.all().order_by('id')   
    page_data = Paginator(data, 3, orphans=1)
    pg_number = request.GET.get('page')
    page_obj = page_data.get_page(pg_number)
    return render(request, 'app1/home.html',{'data':page_obj})
    
def about(request): 
    return render(request, 'app1/about.html')
    
def contact(request):
    if request.method == 'POST':
        fm = contact_form(request.POST)
        if fm.is_valid():
            messages.error(request, 'Your form is submitted successfully!', extra_tags='signup')
            fm.save()
            fm = contact_form()
            return render(request, 'app1/contact.html',{'form':fm})
        return render(request, 'app1/contact.html',{'form':fm})
    fm = contact_form()
    return render(request, 'app1/contact.html',{'form':fm})
    
def dashboard(request):
    if request.user.is_authenticated:
        user = request.user
        user_name = user.get_user_name()

        ip = request.session.get('ip',0)
        ct = cache.get('count', version=user.pk)
        # if ct >= 4:
            # do_logout(request)
            # return HttpResponseRedirect('/login/')

        if user_name != 'admin':
            data = blogs.objects.filter(usernamee=user_name)
        else:
            data = blogs.objects.all()
        if request.method == 'POST':
            fm = blogs_form(request.POST)
            fm.save()
        
        # data = blogs.objects.all().order_by('id')
        page_data = Paginator(data, 3)
        pg_number = request.GET.get('page')
        page_obj = page_data.get_page(pg_number)

        fm = blogs_form()
        return render(request, 'app1/dashboard.html',{'form':fm,'data':page_obj,'username':user_name,'ip':ip,'ct':ct})
    else:
        return HttpResponseRedirect('/login/')

def signup(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            fm = signup_form(request.POST)
            if fm.is_valid():
                user = fm.save()
                group = Group.objects.get(name='simple_user')
                user.groups.add(group)
                messages.error(request, 'Your Account has been Created!', extra_tags='signup')
                fm = signup_form()
                return render(request, 'app1/signup.html',{'form':fm})

            return render(request, 'app1/signup.html',{'form':fm})
        fm = signup_form()
        return render(request, 'app1/signup.html',{'form':fm})
    else:
        return HttpResponseRedirect('/dashboard/')
    
    
def login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            fm = login_form(request=request, data=request.POST)
            uname = request.POST['username']
            passw = request.POST['password']
            if fm.is_valid():
                usr = authenticate(username=uname,password=passw)
                if usr is not None:
                    do_login(request, usr)
                    return HttpResponseRedirect('/dashboard/')  

            messages.error(request, 'Incorrect username or password', extra_tags='login')
            return render(request, 'app1/login.html',{'form':fm})        
        fm = login_form()
        return render(request, 'app1/login.html',{'form':fm})
    else:
        return HttpResponseRedirect('/dashboard/')
     
def logout(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            do_logout(request)
            return HttpResponseRedirect('/login/')
        else:
            return HttpResponse('<h1>404 page not found!</h1>')
    else:
        return HttpResponseRedirect('/login/')


def add_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            user = request.user
            user_name = user.get_user_name()
            obj = blogs(title=request.POST['title'],description=request.POST['description'], usernamee=user_name)
            obj.save()

        fm = blogs_form()
        return render(request, 'app1/addpost.html',{'form':fm})
    else:
        return HttpResponseRedirect('/login/')


def update_post(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            obj = blogs.objects.get(pk=id)
            obj.title = request.POST['title']
            obj.description = request.POST['description']
            obj.save()
            return HttpResponseRedirect('/dashboard/')
        obj = blogs.objects.get(pk=id)
        fm = blogs_form(instance=obj)        
        return render(request, 'app1/updatepost.html',{'form':fm})
    else:
        return HttpResponseRedirect('/login/')


def delete_post(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            obj = blogs.objects.get(pk=id)
            obj.delete()
        return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

app1/templates/app1/about.html
{% extends "app1/base.html" %}
{% load static %}

{% block content %}
    <div class="col-sm-10 container">
        <h2 class="text-white my-5">About Page</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, cum nostrum. Atque aperiam libero neque ab magni, aliquid vitae consectetur quaerat blanditiis in ad at corporis quae nostrum amet alias!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, cum nostrum. Atque aperiam libero neque ab magni, aliquid vitae consectetur quaerat blanditiis in ad at corporis quae nostrum amet alias!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, cum nostrum. Atque aperiam libero neque ab magni, aliquid vitae consectetur quaerat blanditiis in ad at corporis quae nostrum amet alias!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, cum nostrum. Atque aperiam libero neque ab magni, aliquid vitae consectetur quaerat blanditiis in ad at corporis quae nostrum amet alias!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia quidem architecto corporis, quaerat cum iure rem earum! Fuga dolorem aliquid vero aspernatur cupiditate temporibus distinctio ipsa, quis nostrum delectus cumque?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, cum nostrum. Atque aperiam libero neque ab magni, aliquid vitae consectetur quaerat blanditiis in ad at corporis quae nostrum amet alias!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, cum nostrum. Atque aperiam libero neque ab magni, aliquid vitae consectetur quaerat blanditiis in ad at corporis quae nostrum amet alias!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, cum nostrum. Atque aperiam libero neque ab magni, aliquid vitae consectetur quaerat blanditiis in ad at corporis quae nostrum amet alias!</p>
    </div>
{% endblock content %}

app1/templates/app1/addpost.html
{% extends "app1/base.html" %}
{% load static %}

{% block content %}
<div class="col-sm-10 container">
    <h2 class="text-white my-5">Dashboard/ Add Post</h2>

    <form class="row g-3" action="{% url 'addpost' %}" method="post">
        {% csrf_token %}
        {% for fm in form %}
            <div class="col-md-12">
                <label class="form-label" for={{ field.auto_id }}>{{ fm.label_tag }}</label> 
                {{fm}} {{fm.errors|striptags}} <br>
            </div>
        {% endfor %}
        <div class="col-12">
            <button type="submit" class="btn btn-success">Add Post</button>
            <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
        </div>
    </form>
    <br>
    <br>
    <br>
    
</div>
  
{% endblock content %}

app1/templates/app1/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AHMED_BLOGS</title>
    <link rel="stylesheet" href="{% static 'app1/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'app1/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="height: 1.75cm;" >
        <div class="container-fluid mx-2">
          <a class="navbar-brand" href="{% url 'home' %}">AHMED_BLOGS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'contact' %}">Contact</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
                </li> 
              {% endif %}
              {% if not request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
                </li> 
              {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
              <form class="d-flex" action="/logout/" method="post">
                {% csrf_token %}
                <button class="btn btn-success" type="submit">Logout</button>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>

      {% block msg %}
        {% if messages %}
          {% for message in messages %}
            {%if "signup" in message.tags %}
              <div class="alert alert-success alert-dismissible" role="alert">
                {{message}}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endblock msg %}
      
        <div class="container">
          <div class="row">
            <div class="col-sm-8">

            </div>
          </div>

        <div class="row">
          {% block side %}

          {% endblock side %}

          {% block content %}
            
          {% endblock content %}

        </div>
      </div>


      <script src="{% static 'app1/js/popper.js' %}"></script>
      <script src="{% static 'app1/js/bootstrap.js' %}"></script>
</body>
</html>

app1/templates/app1/contact.html
{% extends "app1/base.html" %}
{% load static %}

{% block content %}
    <div class="col-sm-9 container">
        <h2 class="text-white my-5">Contact</h2>

        <form class="row g-3" action="{% url 'contact' %}" method="post">
          {% csrf_token %}
          {% for fm in form %}
              <div class="col-md-12 mb-3">
                  <label class="form-label" for={{ field.auto_id }}>{{ fm.label_tag }}</label> 
                  {{fm}} 
                  {% if fm.errors %}
                    <br> 
                    <div style="color: rgb(255, 2, 2);" >{{fm.errors|striptags}}</div>  
                  {% endif %}
              </div>
          {% endfor %}
          <div class="col-12">
              <button type="submit" class="btn btn-success">Submit</button>
          </div>
      </form>

      <br>
      <br>
      <br>
      <br>
      <br>


 <!-- <form class="row g-3" action="{% url 'contact' %}" method="post">
            {% csrf_token %}
            <div class="col-md-6">
              <label for="inputEmail4" class="form-label">Email</label>
              <input type="email" name="email" class="form-control" id="inputEmail4" placeholder="email" required>
            </div>
            <div class="col-md-6">
              <label for="inputPassword4" class="form-label">Password</label>
              <input type="password" name="pass" class="form-control" id="inputPassword4" placeholder="password" required>
            </div>
            <div class="col-12">
              <label for="inputAddress" class="form-label">Address</label>
              <input type="text" name="address" class="form-control" id="inputAddress" placeholder="1234 Main St" required>
            </div>
            <div class="col-md-12">
              <label for="inputCity" class="form-label">City</label>
              <input type="text" name="city" class="form-control" id="inputCity" placeholder="city name" required>
            </div>
            <div class="col-12">
                <label for="inputtext" class="form-label">Comments</label>
                <textarea class="form-control" name="comments" id="inputtext" rows="3" placeholder="comments" required></textarea>
            </div>
            <div class="col-12">
              <button type="submit" class="btn btn-success">Submit</button>
            </div>
          </form> -->
    </div>
{% endblock content %}

app1/templates/app1/dashboard.html
{% extends "app1/base.html" %}
{% load static %}



{% block content %}

    <div class="col-sm-10 container">
        <h1 class="text-white my-3">Dashboard</h1>
        <h3 class="alert alert-warning my-3">Username : {{username|upper}}</h3>
        <h4 class="alert alert-warning my-3">IP Address : {{ip}}</h4>
        <h4 class="alert alert-warning my-3">user Login count : {{ct}}</h4>
        <br>

        <a href="{% url 'addpost' %}" class="btn btn-success">Add POST</a>
        <h3 class="text-center alert alert-warning mt-4">Show Post Information</h3>
        {% if data %}
          <table class="table table-hover bg-white table-dark">
            <thead>
                <tr class="text-center">
                    <!-- <th class="col" style="width:4%">ID</th> -->
                    <th class="col" style="width:28%">Title</th>
                    <th class="col" style="width:55%">Description</th>
                    <th class="col" style="width:55%">Owner</th>
                    <th class="col" style="width:15%">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in data %}
                    <tr>
                        <!-- <th scope="row">{{i.id}}</th> -->
                        <td>{{i.title}}</td>
                        <td>{{i.description}}</td>
                        <td><b>{{i.usernamee|upper}}</b></td>
                        <td class="text-center">
                            <a href="{% url 'updatepost' i.id %}" class="btn btn-warning btn-sm m-1">Update</a>
                            <form action="{% url 'deletepost' i.id %}" class="d-inline" method="post">
                                {% csrf_token %}
                                {% if perms.app1.delete_blogs %}
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                {% endfor %}        
            </tbody>
          </table>
        {% else %}
          <h3>You have not posted any post!</h3>
        {% endif %}
        <div class="d-flex justify-content-end">
            <span>
                
                {% if data.has_previous %}
                <a class="btn btn-primary" href="?page={{data.previous_page_number}}">Previous</a>
                {% endif %}
                
                <span> {{data.number}} </span>
                
                {% if data.has_next %}
                    <a class="btn btn-primary" href="?page={{data.next_page_number}}">Next</a>
                {% endif %}
                
            </span>
        </div>
        <br>
        <br>
        <br>
    </div>
    

{% endblock content %}

app1/templates/app1/home.html
{% extends "app1/base.html" %}
{% load static %}
{% block content %}
    <div class="col-sm-10 container">
        <h2 class="text-white my-5">Home Page</h2>
        {% for i in data %}
            <div class="jumbotron jumbotron-fluid jumbo-color">
                <div class="container">
                    <br>
                    <h1 class="display-4 font-weight-bold"><b>{{i.title}}</b></h1>
                    <p class="lead">{{i.description}}</p>
                    <h6 style="color:rgb(64, 249, 255)" >Posted by : {{i.usernamee|upper}}</h6>
                    <br>
                </div>
            </div>
            <br>
        {% endfor %}

        <div class="d-flex justify-content-end" >
            <span>
                {% if data.has_previous %}
                    <a class="btn btn-primary" href="?page={{data.previous_page_number}}">Previous</a>
                {% endif %}
    
                <span> {{data.number}} </span>
    
                {% if data.has_next %}
                    <a class="btn btn-primary" href="?page={{data.next_page_number}}">Next</a>
                {% endif %}
            </span>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
{% endblock content %}

app1/templates/app1/login.html
{% extends "app1/base.html" %}

{% block content %}
    
    <div class="col-sm-6 container">
        <h1 class="text-white my-5 text-center">LOGIN!</h1>
        <form class="row g-3" action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {% for fm in form %}
                <div class="col-md-12 mb-3">
                    <label class="form-label" for={{ field.auto_id }}>{{ fm.label_tag }}</label> 
                    {{fm}} {{fm.errors|striptags}} 
                </div>
            {% endfor %}
            {% if messages %}
                {% for message in messages %}
                    {%if "login" in message.tags %}
                    <div class="container" style="color: rgb(255, 2, 2); margin-top: -2px;" >
                        {{message}}
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <div class="col-12">
                <button type="submit" class="btn btn-success">Login</button>
                <a href="{% url 'signup' %}" style="color: rgb(255, 255, 255); margin-left: 15px;" >Register?</a>
            </div>
        </form>
    </div>


{% endblock content %}

app1/templates/app1/signup.html
{% extends "app1/base.html" %}
{% load static %}

{% block content %}

    <div class="col-sm-10 container">
        <h1 class="text-white my-5 text-center">Create an Account!</h1>

        <form class="row g-3" action="{% url 'signup' %}" method="post">
            {% csrf_token %}
            {% for fm in form %}
                <div class="col-md-6">
                    <label class="form-label" for={{ field.auto_id }}>{{ fm.label_tag }}</label> 
                    {{fm}} 
                    <br> 
                    {% if fm.errors %}
                        <div style="color: rgb(255, 2, 2);" >{{fm.errors|striptags}}</div>  
                    {% endif %}
                </div>
            {% endfor %}
            <div class="col-12">
                <button type="submit" class="btn btn-success">Signup</button>
                <a href="{% url 'login' %}" style="color: rgb(255, 255, 255); margin-left: 15px;" >Have an account? LOGIN!</a>
              </div>
        </form>

        
        <br>
        <br>
        <br>
        <br>
        
    </div>

{% endblock content %}

app1/templates/app1/updatepost.html
{% extends "app1/base.html" %}
{% load static %}

{% block content %}
<div class="col-sm-10 container">
    <h1 class="text-white my-5">Dashboard/ Update</h1>
    <!-- <h2 class="text-white my-5">Update Post</h2> -->

    <form class="row g-3" action="" method="post">
        {% csrf_token %}
        {% for fm in form %}
            <div class="col-md-12">
                <label class="form-label" for={{ field.auto_id }}>{{ fm.label_tag }}</label> 
                {{fm}} {{fm.errors|striptags}} <br>
            </div>
        {% endfor %}
        <div class="col-12">
            <button type="submit" class="btn btn-success">Add Post</button>
            <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
        </div>
    </form>
    <br>
    <br>
    <br>
    
</div>
  
{% endblock content %}